---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sheltered-config
  namespace: default

data:
  POSTGRES_DB: "shelteredb"
  POSTGRES_USER: "postgres"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/shelteredb"
  SPRING_DATASOURCE_USERNAME: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: sheltered-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: sheltered-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sheltered-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: shelter-service
  namespace: default
spec:
  selector:
    app: sheltered-shelter-service
  ports:
    - port: 8082
      targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sheltered-shelter-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sheltered-shelter-service
  template:
    metadata:
      labels:
        app: sheltered-shelter-service
    spec:
      containers:
        - name: sheltered-shelter-service
          image: sheltered-shelter-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: sheltered-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: sheltered-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sheltered-secret
                  key: SPRING_DATASOURCE_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: default
spec:
  selector:
    app: sheltered-api-gateway
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sheltered-api-gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sheltered-api-gateway
  template:
    metadata:
      labels:
        app: sheltered-api-gateway
    spec:
      containers:
        - name: sheltered-api-gateway
          image: sheltered-api-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sheltered-secret
                  key: JWT_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: default
spec:
  selector:
    app: sheltered-web-service
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sheltered-web-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sheltered-web-service
  template:
    metadata:
      labels:
        app: sheltered-web-service
    spec:
      containers:
        - name: sheltered-web-service
          image: sheltered-web-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: default
spec:
  selector:
    app: sheltered-user-service
  ports:
    - port: 8083
      targetPort: 8083

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sheltered-user-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sheltered-user-service
  template:
    metadata:
      labels:
        app: sheltered-user-service
    spec:
      containers:
        - name: sheltered-user-service
          image: sheltered-user-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: sheltered-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: sheltered-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sheltered-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: ADMINISTRATOR_EMAIL
              valueFrom:
                secretKeyRef:
                  name: sheltered-secret
                  key: ADMINISTRATOR_EMAIL
            - name: ADMINISTRATOR_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sheltered-secret
                  key: ADMINISTRATOR_EMAIL_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sheltered-secret
                  key: JWT_SECRET
