apiVersion: v1
kind: Secret
metadata:
  name: sheltered-secret
  namespace: default

type: Opaque
stringData:
  POSTGRES_PASSWORD: "DB_password"
  SPRING_DATASOURCE_PASSWORD: "DB_password"
  ADMINISTRATOR_EMAIL: "administrator_email@host.com"
  ADMINISTRATOR_EMAIL_PASSWORD: "email_password"
  JWT_SECRET: "secret_32+_chars_long"